services:
  - type: web
    name: github-repo-tracker
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/github-repo-tracker-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    envVars:
      - key: GITHUB_TOKEN
        sync: false
